apiVersion: v1
kind: Service
metadata:
  name: number-generator-1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: number-generator
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: number-generator-2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: number-generator
  type: NodePort


# kubectl apply -f service.yaml