apiVersion: v1
kind: Service
metadata:
  name: number-generator
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: number-generator
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: number-generator-service-monitor
spec:
  selector:
    matchLabels:
      app: number-generator
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"


# kubectl apply -f service.yaml